// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createDeviceStmt, err = db.PrepareContext(ctx, createDevice); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDevice: %w", err)
	}
	if q.createEmailVerificationStmt, err = db.PrepareContext(ctx, createEmailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEmailVerification: %w", err)
	}
	if q.createRefreshTokenStmt, err = db.PrepareContext(ctx, createRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRefreshToken: %w", err)
	}
	if q.createResetPasswordStmt, err = db.PrepareContext(ctx, createResetPassword); err != nil {
		return nil, fmt.Errorf("error preparing query CreateResetPassword: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createStateTokenStmt, err = db.PrepareContext(ctx, createStateToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStateToken: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deviceStmt, err = db.PrepareContext(ctx, device); err != nil {
		return nil, fmt.Errorf("error preparing query Device: %w", err)
	}
	if q.devicesByUserIDStmt, err = db.PrepareContext(ctx, devicesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DevicesByUserID: %w", err)
	}
	if q.emailVerificationStmt, err = db.PrepareContext(ctx, emailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query EmailVerification: %w", err)
	}
	if q.markEmailVerificationAsExpiredStmt, err = db.PrepareContext(ctx, markEmailVerificationAsExpired); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEmailVerificationAsExpired: %w", err)
	}
	if q.markResetPasswordAsExpiredStmt, err = db.PrepareContext(ctx, markResetPasswordAsExpired); err != nil {
		return nil, fmt.Errorf("error preparing query MarkResetPasswordAsExpired: %w", err)
	}
	if q.refreshTokenStmt, err = db.PrepareContext(ctx, refreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshToken: %w", err)
	}
	if q.resetPasswordStmt, err = db.PrepareContext(ctx, resetPassword); err != nil {
		return nil, fmt.Errorf("error preparing query ResetPassword: %w", err)
	}
	if q.revokeRefreshTokenStmt, err = db.PrepareContext(ctx, revokeRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeRefreshToken: %w", err)
	}
	if q.revokeStateTokenStmt, err = db.PrepareContext(ctx, revokeStateToken); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeStateToken: %w", err)
	}
	if q.setNewPasswordStmt, err = db.PrepareContext(ctx, setNewPassword); err != nil {
		return nil, fmt.Errorf("error preparing query SetNewPassword: %w", err)
	}
	if q.stateTokenStmt, err = db.PrepareContext(ctx, stateToken); err != nil {
		return nil, fmt.Errorf("error preparing query StateToken: %w", err)
	}
	if q.userByEmailStmt, err = db.PrepareContext(ctx, userByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query UserByEmail: %w", err)
	}
	if q.userByIDStmt, err = db.PrepareContext(ctx, userByID); err != nil {
		return nil, fmt.Errorf("error preparing query UserByID: %w", err)
	}
	if q.userSessionStmt, err = db.PrepareContext(ctx, userSession); err != nil {
		return nil, fmt.Errorf("error preparing query UserSession: %w", err)
	}
	if q.userSessionsStmt, err = db.PrepareContext(ctx, userSessions); err != nil {
		return nil, fmt.Errorf("error preparing query UserSessions: %w", err)
	}
	if q.verifyEmailStmt, err = db.PrepareContext(ctx, verifyEmail); err != nil {
		return nil, fmt.Errorf("error preparing query VerifyEmail: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createDeviceStmt != nil {
		if cerr := q.createDeviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeviceStmt: %w", cerr)
		}
	}
	if q.createEmailVerificationStmt != nil {
		if cerr := q.createEmailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEmailVerificationStmt: %w", cerr)
		}
	}
	if q.createRefreshTokenStmt != nil {
		if cerr := q.createRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRefreshTokenStmt: %w", cerr)
		}
	}
	if q.createResetPasswordStmt != nil {
		if cerr := q.createResetPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createResetPasswordStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createStateTokenStmt != nil {
		if cerr := q.createStateTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStateTokenStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deviceStmt != nil {
		if cerr := q.deviceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deviceStmt: %w", cerr)
		}
	}
	if q.devicesByUserIDStmt != nil {
		if cerr := q.devicesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing devicesByUserIDStmt: %w", cerr)
		}
	}
	if q.emailVerificationStmt != nil {
		if cerr := q.emailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing emailVerificationStmt: %w", cerr)
		}
	}
	if q.markEmailVerificationAsExpiredStmt != nil {
		if cerr := q.markEmailVerificationAsExpiredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEmailVerificationAsExpiredStmt: %w", cerr)
		}
	}
	if q.markResetPasswordAsExpiredStmt != nil {
		if cerr := q.markResetPasswordAsExpiredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markResetPasswordAsExpiredStmt: %w", cerr)
		}
	}
	if q.refreshTokenStmt != nil {
		if cerr := q.refreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshTokenStmt: %w", cerr)
		}
	}
	if q.resetPasswordStmt != nil {
		if cerr := q.resetPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetPasswordStmt: %w", cerr)
		}
	}
	if q.revokeRefreshTokenStmt != nil {
		if cerr := q.revokeRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeRefreshTokenStmt: %w", cerr)
		}
	}
	if q.revokeStateTokenStmt != nil {
		if cerr := q.revokeStateTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeStateTokenStmt: %w", cerr)
		}
	}
	if q.setNewPasswordStmt != nil {
		if cerr := q.setNewPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setNewPasswordStmt: %w", cerr)
		}
	}
	if q.stateTokenStmt != nil {
		if cerr := q.stateTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing stateTokenStmt: %w", cerr)
		}
	}
	if q.userByEmailStmt != nil {
		if cerr := q.userByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userByEmailStmt: %w", cerr)
		}
	}
	if q.userByIDStmt != nil {
		if cerr := q.userByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userByIDStmt: %w", cerr)
		}
	}
	if q.userSessionStmt != nil {
		if cerr := q.userSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userSessionStmt: %w", cerr)
		}
	}
	if q.userSessionsStmt != nil {
		if cerr := q.userSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userSessionsStmt: %w", cerr)
		}
	}
	if q.verifyEmailStmt != nil {
		if cerr := q.verifyEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifyEmailStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db DBTX
	tx *sql.Tx
	createDeviceStmt                   *sql.Stmt
	createEmailVerificationStmt        *sql.Stmt
	createRefreshTokenStmt             *sql.Stmt
	createResetPasswordStmt            *sql.Stmt
	createSessionStmt                  *sql.Stmt
	createStateTokenStmt               *sql.Stmt
	createUserStmt                     *sql.Stmt
	deviceStmt                         *sql.Stmt
	devicesByUserIDStmt                *sql.Stmt
	emailVerificationStmt              *sql.Stmt
	markEmailVerificationAsExpiredStmt *sql.Stmt
	markResetPasswordAsExpiredStmt     *sql.Stmt
	refreshTokenStmt                   *sql.Stmt
	resetPasswordStmt                  *sql.Stmt
	revokeRefreshTokenStmt             *sql.Stmt
	revokeStateTokenStmt               *sql.Stmt
	setNewPasswordStmt                 *sql.Stmt
	stateTokenStmt                     *sql.Stmt
	userByEmailStmt                    *sql.Stmt
	userByIDStmt                       *sql.Stmt
	userSessionStmt                    *sql.Stmt
	userSessionsStmt                   *sql.Stmt
	verifyEmailStmt                    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		createDeviceStmt:                   q.createDeviceStmt,
		createEmailVerificationStmt:        q.createEmailVerificationStmt,
		createRefreshTokenStmt:             q.createRefreshTokenStmt,
		createResetPasswordStmt:            q.createResetPasswordStmt,
		createSessionStmt:                  q.createSessionStmt,
		createStateTokenStmt:               q.createStateTokenStmt,
		createUserStmt:                     q.createUserStmt,
		deviceStmt:                         q.deviceStmt,
		devicesByUserIDStmt:                q.devicesByUserIDStmt,
		emailVerificationStmt:              q.emailVerificationStmt,
		markEmailVerificationAsExpiredStmt: q.markEmailVerificationAsExpiredStmt,
		markResetPasswordAsExpiredStmt:     q.markResetPasswordAsExpiredStmt,
		refreshTokenStmt:                   q.refreshTokenStmt,
		resetPasswordStmt:                  q.resetPasswordStmt,
		revokeRefreshTokenStmt:             q.revokeRefreshTokenStmt,
		revokeStateTokenStmt:               q.revokeStateTokenStmt,
		setNewPasswordStmt:                 q.setNewPasswordStmt,
		stateTokenStmt:                     q.stateTokenStmt,
		userByEmailStmt:                    q.userByEmailStmt,
		userByIDStmt:                       q.userByIDStmt,
		userSessionStmt:                    q.userSessionStmt,
		userSessionsStmt:                   q.userSessionsStmt,
		verifyEmailStmt:                    q.verifyEmailStmt,
	}
}
