// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createOrganizationStmt, err = db.PrepareContext(ctx, createOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrganization: %w", err)
	}
	if q.createOrganizationMemberStmt, err = db.PrepareContext(ctx, createOrganizationMember); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrganizationMember: %w", err)
	}
	if q.createOrganizationMetadataStmt, err = db.PrepareContext(ctx, createOrganizationMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrganizationMetadata: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteOrganizationMemberByClerkIDsStmt, err = db.PrepareContext(ctx, deleteOrganizationMemberByClerkIDs); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOrganizationMemberByClerkIDs: %w", err)
	}
	if q.deleteOrganizationMetadataByOrganizationIDStmt, err = db.PrepareContext(ctx, deleteOrganizationMetadataByOrganizationID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOrganizationMetadataByOrganizationID: %w", err)
	}
	if q.getOrganizationByClerkIDStmt, err = db.PrepareContext(ctx, getOrganizationByClerkID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationByClerkID: %w", err)
	}
	if q.getOrganizationMembersByOrganizationIDStmt, err = db.PrepareContext(ctx, getOrganizationMembersByOrganizationID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationMembersByOrganizationID: %w", err)
	}
	if q.getOrganizationMembersByUserClerkIDStmt, err = db.PrepareContext(ctx, getOrganizationMembersByUserClerkID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationMembersByUserClerkID: %w", err)
	}
	if q.getOrganizationMetadataByOrganizationIDStmt, err = db.PrepareContext(ctx, getOrganizationMetadataByOrganizationID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationMetadataByOrganizationID: %w", err)
	}
	if q.getOrganizationsByUserClerkIDStmt, err = db.PrepareContext(ctx, getOrganizationsByUserClerkID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationsByUserClerkID: %w", err)
	}
	if q.getUserByClerkIDStmt, err = db.PrepareContext(ctx, getUserByClerkID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByClerkID: %w", err)
	}
	if q.updateOrganizationStmt, err = db.PrepareContext(ctx, updateOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrganization: %w", err)
	}
	if q.updateOrganizationMetadataStmt, err = db.PrepareContext(ctx, updateOrganizationMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrganizationMetadata: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createOrganizationStmt != nil {
		if cerr := q.createOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrganizationStmt: %w", cerr)
		}
	}
	if q.createOrganizationMemberStmt != nil {
		if cerr := q.createOrganizationMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrganizationMemberStmt: %w", cerr)
		}
	}
	if q.createOrganizationMetadataStmt != nil {
		if cerr := q.createOrganizationMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrganizationMetadataStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteOrganizationMemberByClerkIDsStmt != nil {
		if cerr := q.deleteOrganizationMemberByClerkIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOrganizationMemberByClerkIDsStmt: %w", cerr)
		}
	}
	if q.deleteOrganizationMetadataByOrganizationIDStmt != nil {
		if cerr := q.deleteOrganizationMetadataByOrganizationIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOrganizationMetadataByOrganizationIDStmt: %w", cerr)
		}
	}
	if q.getOrganizationByClerkIDStmt != nil {
		if cerr := q.getOrganizationByClerkIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationByClerkIDStmt: %w", cerr)
		}
	}
	if q.getOrganizationMembersByOrganizationIDStmt != nil {
		if cerr := q.getOrganizationMembersByOrganizationIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationMembersByOrganizationIDStmt: %w", cerr)
		}
	}
	if q.getOrganizationMembersByUserClerkIDStmt != nil {
		if cerr := q.getOrganizationMembersByUserClerkIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationMembersByUserClerkIDStmt: %w", cerr)
		}
	}
	if q.getOrganizationMetadataByOrganizationIDStmt != nil {
		if cerr := q.getOrganizationMetadataByOrganizationIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationMetadataByOrganizationIDStmt: %w", cerr)
		}
	}
	if q.getOrganizationsByUserClerkIDStmt != nil {
		if cerr := q.getOrganizationsByUserClerkIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationsByUserClerkIDStmt: %w", cerr)
		}
	}
	if q.getUserByClerkIDStmt != nil {
		if cerr := q.getUserByClerkIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByClerkIDStmt: %w", cerr)
		}
	}
	if q.updateOrganizationStmt != nil {
		if cerr := q.updateOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrganizationStmt: %w", cerr)
		}
	}
	if q.updateOrganizationMetadataStmt != nil {
		if cerr := q.updateOrganizationMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrganizationMetadataStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                             DBTX
	tx                                             *sql.Tx
	createOrganizationStmt                         *sql.Stmt
	createOrganizationMemberStmt                   *sql.Stmt
	createOrganizationMetadataStmt                 *sql.Stmt
	createUserStmt                                 *sql.Stmt
	deleteOrganizationMemberByClerkIDsStmt         *sql.Stmt
	deleteOrganizationMetadataByOrganizationIDStmt *sql.Stmt
	getOrganizationByClerkIDStmt                   *sql.Stmt
	getOrganizationMembersByOrganizationIDStmt     *sql.Stmt
	getOrganizationMembersByUserClerkIDStmt        *sql.Stmt
	getOrganizationMetadataByOrganizationIDStmt    *sql.Stmt
	getOrganizationsByUserClerkIDStmt              *sql.Stmt
	getUserByClerkIDStmt                           *sql.Stmt
	updateOrganizationStmt                         *sql.Stmt
	updateOrganizationMetadataStmt                 *sql.Stmt
	updateUserStmt                                 *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		createOrganizationStmt:                 q.createOrganizationStmt,
		createOrganizationMemberStmt:           q.createOrganizationMemberStmt,
		createOrganizationMetadataStmt:         q.createOrganizationMetadataStmt,
		createUserStmt:                         q.createUserStmt,
		deleteOrganizationMemberByClerkIDsStmt: q.deleteOrganizationMemberByClerkIDsStmt,
		deleteOrganizationMetadataByOrganizationIDStmt: q.deleteOrganizationMetadataByOrganizationIDStmt,
		getOrganizationByClerkIDStmt:                   q.getOrganizationByClerkIDStmt,
		getOrganizationMembersByOrganizationIDStmt:     q.getOrganizationMembersByOrganizationIDStmt,
		getOrganizationMembersByUserClerkIDStmt:        q.getOrganizationMembersByUserClerkIDStmt,
		getOrganizationMetadataByOrganizationIDStmt:    q.getOrganizationMetadataByOrganizationIDStmt,
		getOrganizationsByUserClerkIDStmt:              q.getOrganizationsByUserClerkIDStmt,
		getUserByClerkIDStmt:                           q.getUserByClerkIDStmt,
		updateOrganizationStmt:                         q.updateOrganizationStmt,
		updateOrganizationMetadataStmt:                 q.updateOrganizationMetadataStmt,
		updateUserStmt:                                 q.updateUserStmt,
	}
}
