// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: member.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createOrganizationMember = `-- name: CreateOrganizationMember :exec
INSERT INTO organization_members (user_id, organization_id, clerk_user_id, clerk_org_id, role)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrganizationMemberParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ClerkUserID    string    `json:"clerk_user_id"`
	ClerkOrgID     string    `json:"clerk_org_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) error {
	_, err := q.exec(ctx, q.createOrganizationMemberStmt, createOrganizationMember,
		arg.UserID,
		arg.OrganizationID,
		arg.ClerkUserID,
		arg.ClerkOrgID,
		arg.Role,
	)
	return err
}

const deleteOrganizationMemberByClerkIDs = `-- name: DeleteOrganizationMemberByClerkIDs :exec
DELETE FROM organization_members
WHERE clerk_user_id = $1 AND clerk_org_id = $2
`

type DeleteOrganizationMemberByClerkIDsParams struct {
	ClerkUserID string `json:"clerk_user_id"`
	ClerkOrgID  string `json:"clerk_org_id"`
}

func (q *Queries) DeleteOrganizationMemberByClerkIDs(ctx context.Context, arg DeleteOrganizationMemberByClerkIDsParams) error {
	_, err := q.exec(ctx, q.deleteOrganizationMemberByClerkIDsStmt, deleteOrganizationMemberByClerkIDs, arg.ClerkUserID, arg.ClerkOrgID)
	return err
}

const getOrganizationMembersByOrganizationID = `-- name: GetOrganizationMembersByOrganizationID :many
SELECT user_id, organization_id, clerk_user_id, clerk_org_id, role, joined_at
FROM organization_members
WHERE organization_id = $1
`

func (q *Queries) GetOrganizationMembersByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]OrganizationMember, error) {
	rows, err := q.query(ctx, q.getOrganizationMembersByOrganizationIDStmt, getOrganizationMembersByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMember
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.ClerkUserID,
			&i.ClerkOrgID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationMembersByUserClerkID = `-- name: GetOrganizationMembersByUserClerkID :many
SELECT user_id, organization_id, clerk_user_id, clerk_org_id, role, joined_at
FROM organization_members
WHERE clerk_user_id = $1
`

func (q *Queries) GetOrganizationMembersByUserClerkID(ctx context.Context, clerkUserID string) ([]OrganizationMember, error) {
	rows, err := q.query(ctx, q.getOrganizationMembersByUserClerkIDStmt, getOrganizationMembersByUserClerkID, clerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMember
	for rows.Next() {
		var i OrganizationMember
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.ClerkUserID,
			&i.ClerkOrgID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationMemberByClerkIDs = `-- name: UpdateOrganizationMemberByClerkIDs :exec
UPDATE organization_members
SET role = $3
WHERE clerk_user_id = $1 AND clerk_org_id = $2
`

type UpdateOrganizationMemberByClerkIDsParams struct {
	ClerkUserID string `json:"clerk_user_id"`
	ClerkOrgID  string `json:"clerk_org_id"`
	Role        string `json:"role"`
}

func (q *Queries) UpdateOrganizationMemberByClerkIDs(ctx context.Context, arg UpdateOrganizationMemberByClerkIDsParams) error {
	_, err := q.exec(ctx, q.updateOrganizationMemberByClerkIDsStmt, updateOrganizationMemberByClerkIDs, arg.ClerkUserID, arg.ClerkOrgID, arg.Role)
	return err
}
