// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: metadata.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOrganizationMetadata = `-- name: CreateOrganizationMetadata :exec
INSERT INTO organization_metadata (organization_id, company_size, team_size, use_cases, observability_stack)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrganizationMetadataParams struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	CompanySize        string    `json:"company_size"`
	TeamSize           string    `json:"team_size"`
	UseCases           []string  `json:"use_cases"`
	ObservabilityStack []string  `json:"observability_stack"`
}

func (q *Queries) CreateOrganizationMetadata(ctx context.Context, arg CreateOrganizationMetadataParams) error {
	_, err := q.exec(ctx, q.createOrganizationMetadataStmt, createOrganizationMetadata,
		arg.OrganizationID,
		arg.CompanySize,
		arg.TeamSize,
		pq.Array(arg.UseCases),
		pq.Array(arg.ObservabilityStack),
	)
	return err
}

const deleteOrganizationMetadataByOrganizationID = `-- name: DeleteOrganizationMetadataByOrganizationID :exec
DELETE FROM organization_metadata
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationMetadataByOrganizationID(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteOrganizationMetadataByOrganizationIDStmt, deleteOrganizationMetadataByOrganizationID, organizationID)
	return err
}

const getOrganizationMetadataByOrganizationID = `-- name: GetOrganizationMetadataByOrganizationID :one
SELECT organization_id, company_size, team_size, use_cases, observability_stack, completed_at, updated_at
FROM organization_metadata
WHERE organization_id = $1
`

func (q *Queries) GetOrganizationMetadataByOrganizationID(ctx context.Context, organizationID uuid.UUID) (OrganizationMetadatum, error) {
	row := q.queryRow(ctx, q.getOrganizationMetadataByOrganizationIDStmt, getOrganizationMetadataByOrganizationID, organizationID)
	var i OrganizationMetadatum
	err := row.Scan(
		&i.OrganizationID,
		&i.CompanySize,
		&i.TeamSize,
		pq.Array(&i.UseCases),
		pq.Array(&i.ObservabilityStack),
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationMetadata = `-- name: UpdateOrganizationMetadata :exec
UPDATE organization_metadata
SET company_size = $2, team_size = $3, use_cases = $4, observability_stack = $5, updated_at = NOW()
WHERE organization_id = $1
`

type UpdateOrganizationMetadataParams struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	CompanySize        string    `json:"company_size"`
	TeamSize           string    `json:"team_size"`
	UseCases           []string  `json:"use_cases"`
	ObservabilityStack []string  `json:"observability_stack"`
}

func (q *Queries) UpdateOrganizationMetadata(ctx context.Context, arg UpdateOrganizationMetadataParams) error {
	_, err := q.exec(ctx, q.updateOrganizationMetadataStmt, updateOrganizationMetadata,
		arg.OrganizationID,
		arg.CompanySize,
		arg.TeamSize,
		pq.Array(arg.UseCases),
		pq.Array(arg.ObservabilityStack),
	)
	return err
}
