// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"

	"github.com/google/uuid"
)

type Organization struct {
	ID              uuid.UUID     `json:"id"`
	ClerkOrgID      string        `json:"clerk_org_id"`
	Name            string        `json:"name"`
	Slug            string        `json:"slug"`
	CreatedByUserID uuid.NullUUID `json:"created_by_user_id"`
	CreatedAt       sql.NullTime  `json:"created_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
}

type OrganizationMember struct {
	UserID         uuid.UUID    `json:"user_id"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	ClerkUserID    string       `json:"clerk_user_id"`
	ClerkOrgID     string       `json:"clerk_org_id"`
	Role           string       `json:"role"`
	JoinedAt       sql.NullTime `json:"joined_at"`
}

type OrganizationMetadatum struct {
	OrganizationID     uuid.UUID    `json:"organization_id"`
	CompanySize        string       `json:"company_size"`
	TeamSize           string       `json:"team_size"`
	UseCases           []string     `json:"use_cases"`
	ObservabilityStack []string     `json:"observability_stack"`
	CompletedAt        sql.NullTime `json:"completed_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID    `json:"id"`
	ClerkUserID string       `json:"clerk_user_id"`
	Email       string       `json:"email"`
	FirstName   string       `json:"first_name"`
	LastName    string       `json:"last_name"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}
