// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organization.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (clerk_org_id, name, slug, created_by_user_id)
VALUES ($1, $2, $3, $4)
`

type CreateOrganizationParams struct {
	ClerkOrgID      string        `json:"clerk_org_id"`
	Name            string        `json:"name"`
	Slug            string        `json:"slug"`
	CreatedByUserID uuid.NullUUID `json:"created_by_user_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.exec(ctx, q.createOrganizationStmt, createOrganization,
		arg.ClerkOrgID,
		arg.Name,
		arg.Slug,
		arg.CreatedByUserID,
	)
	return err
}

const deleteOrganizationByClerkID = `-- name: DeleteOrganizationByClerkID :exec
DELETE FROM organizations
WHERE clerk_org_id = $1
`

func (q *Queries) DeleteOrganizationByClerkID(ctx context.Context, clerkOrgID string) error {
	_, err := q.exec(ctx, q.deleteOrganizationByClerkIDStmt, deleteOrganizationByClerkID, clerkOrgID)
	return err
}

const getOrganizationByClerkID = `-- name: GetOrganizationByClerkID :one
SELECT id, clerk_org_id, name, slug, created_by_user_id, created_at, updated_at
FROM organizations
WHERE clerk_org_id = $1
`

func (q *Queries) GetOrganizationByClerkID(ctx context.Context, clerkOrgID string) (Organization, error) {
	row := q.queryRow(ctx, q.getOrganizationByClerkIDStmt, getOrganizationByClerkID, clerkOrgID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationsByUserClerkID = `-- name: GetOrganizationsByUserClerkID :many
SELECT o.id, o.clerk_org_id, o.name, o.slug, o.created_by_user_id, o.created_at, o.updated_at
FROM organizations o
INNER JOIN organization_members om ON o.id = om.organization_id
WHERE om.clerk_user_id = $1
`

func (q *Queries) GetOrganizationsByUserClerkID(ctx context.Context, clerkUserID string) ([]Organization, error) {
	rows, err := q.query(ctx, q.getOrganizationsByUserClerkIDStmt, getOrganizationsByUserClerkID, clerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.ClerkOrgID,
			&i.Name,
			&i.Slug,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = $2, slug = $3, updated_at = NOW()
WHERE clerk_org_id = $1
`

type UpdateOrganizationParams struct {
	ClerkOrgID string `json:"clerk_org_id"`
	Name       string `json:"name"`
	Slug       string `json:"slug"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.exec(ctx, q.updateOrganizationStmt, updateOrganization, arg.ClerkOrgID, arg.Name, arg.Slug)
	return err
}
