// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) error
	CreateOrganizationMetadata(ctx context.Context, arg CreateOrganizationMetadataParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteOrganizationMemberByClerkIDs(ctx context.Context, arg DeleteOrganizationMemberByClerkIDsParams) error
	DeleteOrganizationMetadataByOrganizationID(ctx context.Context, organizationID uuid.UUID) error
	GetOrganizationByClerkID(ctx context.Context, clerkOrgID string) (Organization, error)
	GetOrganizationMembersByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]OrganizationMember, error)
	GetOrganizationMembersByUserClerkID(ctx context.Context, clerkUserID string) ([]OrganizationMember, error)
	GetOrganizationMetadataByOrganizationID(ctx context.Context, organizationID uuid.UUID) (OrganizationMetadatum, error)
	GetOrganizationsByUserClerkID(ctx context.Context, clerkUserID string) ([]Organization, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdateOrganizationMetadata(ctx context.Context, arg UpdateOrganizationMetadataParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
