// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: session.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :exec
insert into device (device_id, user_id, device_fingerprint, name, os, brand)
values ($1, $2, $3, $4, $5, $6)
`

type CreateDeviceParams struct {
	DeviceID          uuid.UUID `json:"device_id"`
	UserID            uuid.UUID `json:"user_id"`
	DeviceFingerprint string    `json:"device_fingerprint"`
	Name              string    `json:"name"`
	Os                string    `json:"os"`
	Brand             string    `json:"brand"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.exec(ctx, q.createDeviceStmt, createDevice,
		arg.DeviceID,
		arg.UserID,
		arg.DeviceFingerprint,
		arg.Name,
		arg.Os,
		arg.Brand,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
insert into refresh_token (token_id, user_id, session_id, token_hash, expiry_at)
values ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	TokenID   uuid.UUID `json:"token_id"`
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
	TokenHash string    `json:"token_hash"`
	ExpiryAt  time.Time `json:"expiry_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.exec(ctx, q.createRefreshTokenStmt, createRefreshToken,
		arg.TokenID,
		arg.UserID,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiryAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
insert into user_session (user_id, device_id, session_id, user_agent,
ip_address, ip_country_iso, timezone)
values ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	DeviceID     uuid.UUID `json:"device_id"`
	SessionID    uuid.UUID `json:"session_id"`
	UserAgent    string    `json:"user_agent"`
	IpAddress    string    `json:"ip_address"`
	IpCountryIso string    `json:"ip_country_iso"`
	Timezone     string    `json:"timezone"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.exec(ctx, q.createSessionStmt, createSession,
		arg.UserID,
		arg.DeviceID,
		arg.SessionID,
		arg.UserAgent,
		arg.IpAddress,
		arg.IpCountryIso,
		arg.Timezone,
	)
	return err
}

const device = `-- name: Device :one
select device_id, user_id, device_fingerprint, name, os, brand
from device where device_id = $1
`

func (q *Queries) Device(ctx context.Context, deviceID uuid.UUID) (Device, error) {
	row := q.queryRow(ctx, q.deviceStmt, device, deviceID)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.DeviceFingerprint,
		&i.Name,
		&i.Os,
		&i.Brand,
	)
	return i, err
}

const devicesByUserID = `-- name: DevicesByUserID :many
select device_id, user_id, device_fingerprint, name, os, brand
from device where user_id = $1
`

func (q *Queries) DevicesByUserID(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.query(ctx, q.devicesByUserIDStmt, devicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DeviceID,
			&i.UserID,
			&i.DeviceFingerprint,
			&i.Name,
			&i.Os,
			&i.Brand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshToken = `-- name: RefreshToken :one
select token_id, user_id, session_id, token_hash, expiry_at, created_at, revoked
from refresh_token where token_id = $1 and revoked = false
`

func (q *Queries) RefreshToken(ctx context.Context, tokenID uuid.UUID) (RefreshToken, error) {
	row := q.queryRow(ctx, q.refreshTokenStmt, refreshToken, tokenID)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.ExpiryAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
update refresh_token set revoked = true, expiry_at = now() where token_id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.exec(ctx, q.revokeRefreshTokenStmt, revokeRefreshToken, tokenID)
	return err
}

const userSession = `-- name: UserSession :one
select user_id, device_id, session_id, user_agent, ip_address, ip_country_iso,
last_activity_at, created_at, timezone, is_expired
from user_session where session_id = $1 and is_expired = false
`

func (q *Queries) UserSession(ctx context.Context, sessionID uuid.UUID) (UserSession, error) {
	row := q.queryRow(ctx, q.userSessionStmt, userSession, sessionID)
	var i UserSession
	err := row.Scan(
		&i.UserID,
		&i.DeviceID,
		&i.SessionID,
		&i.UserAgent,
		&i.IpAddress,
		&i.IpCountryIso,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.Timezone,
		&i.IsExpired,
	)
	return i, err
}

const userSessions = `-- name: UserSessions :many
select user_id, device_id, session_id, user_agent, ip_address, ip_country_iso,
last_activity_at, created_at, timezone, is_expired
from user_session where user_id = $1 and is_expired = false
`

func (q *Queries) UserSessions(ctx context.Context, userID uuid.UUID) ([]UserSession, error) {
	rows, err := q.query(ctx, q.userSessionsStmt, userSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.UserID,
			&i.DeviceID,
			&i.SessionID,
			&i.UserAgent,
			&i.IpAddress,
			&i.IpCountryIso,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.Timezone,
			&i.IsExpired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
