// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: state_token.sql

package postgres

import (
	"context"
	"time"
)

const createStateToken = `-- name: CreateStateToken :exec
insert into  google_state_token (token, expires_at) values ($1, $2)
`

type CreateStateTokenParams struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateStateToken(ctx context.Context, arg CreateStateTokenParams) error {
	_, err := q.exec(ctx, q.createStateTokenStmt, createStateToken, arg.Token, arg.ExpiresAt)
	return err
}

const revokeStateToken = `-- name: RevokeStateToken :exec
update google_state_token set revoked = true, revoked_at = now() where token = $1
`

func (q *Queries) RevokeStateToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.revokeStateTokenStmt, revokeStateToken, token)
	return err
}

const stateToken = `-- name: StateToken :one
select token, revoked, revoked_at, expires_at, created_at from google_state_token where token = $1
`

func (q *Queries) StateToken(ctx context.Context, token string) (GoogleStateToken, error) {
	row := q.queryRow(ctx, q.stateTokenStmt, stateToken, token)
	var i GoogleStateToken
	err := row.Scan(
		&i.Token,
		&i.Revoked,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
