// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
insert into email_verification (verification_id, user_id, email, expiry_at)
values ($1, $2, $3, $4)
`

type CreateEmailVerificationParams struct {
	VerificationID uuid.UUID `json:"verification_id"`
	UserID         uuid.UUID `json:"user_id"`
	Email          string    `json:"email"`
	ExpiryAt       time.Time `json:"expiry_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.exec(ctx, q.createEmailVerificationStmt, createEmailVerification,
		arg.VerificationID,
		arg.UserID,
		arg.Email,
		arg.ExpiryAt,
	)
	return err
}

const createResetPassword = `-- name: CreateResetPassword :exec
insert into reset_password (reset_id, user_id, expiry_at)
values ($1, $2, $3)
`

type CreateResetPasswordParams struct {
	ResetID  uuid.UUID `json:"reset_id"`
	UserID   uuid.UUID `json:"user_id"`
	ExpiryAt time.Time `json:"expiry_at"`
}

func (q *Queries) CreateResetPassword(ctx context.Context, arg CreateResetPasswordParams) error {
	_, err := q.exec(ctx, q.createResetPasswordStmt, createResetPassword, arg.ResetID, arg.UserID, arg.ExpiryAt)
	return err
}

const createUser = `-- name: CreateUser :exec
insert into users (user_id, email, password_hash)
values ($1, $2, $3)
`

type CreateUserParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.exec(ctx, q.createUserStmt, createUser, arg.UserID, arg.Email, arg.PasswordHash)
	return err
}

const emailVerification = `-- name: EmailVerification :one
select verification_id, user_id, email, expiry_at from email_verification where verification_id = $1
`

type EmailVerificationRow struct {
	VerificationID uuid.UUID `json:"verification_id"`
	UserID         uuid.UUID `json:"user_id"`
	Email          string    `json:"email"`
	ExpiryAt       time.Time `json:"expiry_at"`
}

func (q *Queries) EmailVerification(ctx context.Context, verificationID uuid.UUID) (EmailVerificationRow, error) {
	row := q.queryRow(ctx, q.emailVerificationStmt, emailVerification, verificationID)
	var i EmailVerificationRow
	err := row.Scan(
		&i.VerificationID,
		&i.UserID,
		&i.Email,
		&i.ExpiryAt,
	)
	return i, err
}

const markEmailVerificationAsExpired = `-- name: MarkEmailVerificationAsExpired :exec
update email_verification set expiry_at = now() where verification_id = $1
`

func (q *Queries) MarkEmailVerificationAsExpired(ctx context.Context, verificationID uuid.UUID) error {
	_, err := q.exec(ctx, q.markEmailVerificationAsExpiredStmt, markEmailVerificationAsExpired, verificationID)
	return err
}

const markResetPasswordAsExpired = `-- name: MarkResetPasswordAsExpired :exec
update reset_password set expiry_at = now() where reset_id = $1
`

func (q *Queries) MarkResetPasswordAsExpired(ctx context.Context, resetID uuid.UUID) error {
	_, err := q.exec(ctx, q.markResetPasswordAsExpiredStmt, markResetPasswordAsExpired, resetID)
	return err
}

const resetPassword = `-- name: ResetPassword :one
select reset_id, user_id, expiry_at from reset_password where reset_id = $1
`

type ResetPasswordRow struct {
	ResetID  uuid.UUID `json:"reset_id"`
	UserID   uuid.UUID `json:"user_id"`
	ExpiryAt time.Time `json:"expiry_at"`
}

func (q *Queries) ResetPassword(ctx context.Context, resetID uuid.UUID) (ResetPasswordRow, error) {
	row := q.queryRow(ctx, q.resetPasswordStmt, resetPassword, resetID)
	var i ResetPasswordRow
	err := row.Scan(&i.ResetID, &i.UserID, &i.ExpiryAt)
	return i, err
}

const setNewPassword = `-- name: SetNewPassword :exec
update users set password_hash = $2, updated_at = now() where user_id = $1
`

type SetNewPasswordParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) SetNewPassword(ctx context.Context, arg SetNewPasswordParams) error {
	_, err := q.exec(ctx, q.setNewPasswordStmt, setNewPassword, arg.UserID, arg.PasswordHash)
	return err
}

const userByEmail = `-- name: UserByEmail :one
select user_id, email, password_hash from users where email = $1
`

type UserByEmailRow struct {
	UserID       uuid.UUID `json:"user_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UserByEmail(ctx context.Context, email string) (UserByEmailRow, error) {
	row := q.queryRow(ctx, q.userByEmailStmt, userByEmail, email)
	var i UserByEmailRow
	err := row.Scan(&i.UserID, &i.Email, &i.PasswordHash)
	return i, err
}

const userByID = `-- name: UserByID :one
select user_id, email, password_hash, is_email_verified, created_at, updated_at from users where user_id = $1
`

func (q *Queries) UserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.userByIDStmt, userByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyEmail = `-- name: VerifyEmail :exec
update users set is_email_verified = true, updated_at = now() where user_id = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.verifyEmailStmt, verifyEmail, userID)
	return err
}
