// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.authorizeDeviceCodeStmt, err = db.PrepareContext(ctx, authorizeDeviceCode); err != nil {
		return nil, fmt.Errorf("error preparing query AuthorizeDeviceCode: %w", err)
	}
	if q.createDeviceCodeStmt, err = db.PrepareContext(ctx, createDeviceCode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDeviceCode: %w", err)
	}
	if q.createDeviceTokenStmt, err = db.PrepareContext(ctx, createDeviceToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDeviceToken: %w", err)
	}
	if q.deleteExpiredDeviceCodesStmt, err = db.PrepareContext(ctx, deleteExpiredDeviceCodes); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredDeviceCodes: %w", err)
	}
	if q.getDeviceCodeByDeviceCodeStmt, err = db.PrepareContext(ctx, getDeviceCodeByDeviceCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceCodeByDeviceCode: %w", err)
	}
	if q.getDeviceCodeByUserCodeStmt, err = db.PrepareContext(ctx, getDeviceCodeByUserCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceCodeByUserCode: %w", err)
	}
	if q.getDeviceTokenByAccessTokenStmt, err = db.PrepareContext(ctx, getDeviceTokenByAccessToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceTokenByAccessToken: %w", err)
	}
	if q.getDeviceTokenByRefreshTokenStmt, err = db.PrepareContext(ctx, getDeviceTokenByRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeviceTokenByRefreshToken: %w", err)
	}
	if q.markDeviceCodeAsUsedStmt, err = db.PrepareContext(ctx, markDeviceCodeAsUsed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkDeviceCodeAsUsed: %w", err)
	}
	if q.revokeAllDeviceTokensForUserStmt, err = db.PrepareContext(ctx, revokeAllDeviceTokensForUser); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeAllDeviceTokensForUser: %w", err)
	}
	if q.revokeDeviceTokenStmt, err = db.PrepareContext(ctx, revokeDeviceToken); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeDeviceToken: %w", err)
	}
	if q.updateDeviceTokensStmt, err = db.PrepareContext(ctx, updateDeviceTokens); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeviceTokens: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.authorizeDeviceCodeStmt != nil {
		if cerr := q.authorizeDeviceCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing authorizeDeviceCodeStmt: %w", cerr)
		}
	}
	if q.createDeviceCodeStmt != nil {
		if cerr := q.createDeviceCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeviceCodeStmt: %w", cerr)
		}
	}
	if q.createDeviceTokenStmt != nil {
		if cerr := q.createDeviceTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeviceTokenStmt: %w", cerr)
		}
	}
	if q.deleteExpiredDeviceCodesStmt != nil {
		if cerr := q.deleteExpiredDeviceCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredDeviceCodesStmt: %w", cerr)
		}
	}
	if q.getDeviceCodeByDeviceCodeStmt != nil {
		if cerr := q.getDeviceCodeByDeviceCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceCodeByDeviceCodeStmt: %w", cerr)
		}
	}
	if q.getDeviceCodeByUserCodeStmt != nil {
		if cerr := q.getDeviceCodeByUserCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceCodeByUserCodeStmt: %w", cerr)
		}
	}
	if q.getDeviceTokenByAccessTokenStmt != nil {
		if cerr := q.getDeviceTokenByAccessTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceTokenByAccessTokenStmt: %w", cerr)
		}
	}
	if q.getDeviceTokenByRefreshTokenStmt != nil {
		if cerr := q.getDeviceTokenByRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeviceTokenByRefreshTokenStmt: %w", cerr)
		}
	}
	if q.markDeviceCodeAsUsedStmt != nil {
		if cerr := q.markDeviceCodeAsUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markDeviceCodeAsUsedStmt: %w", cerr)
		}
	}
	if q.revokeAllDeviceTokensForUserStmt != nil {
		if cerr := q.revokeAllDeviceTokensForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeAllDeviceTokensForUserStmt: %w", cerr)
		}
	}
	if q.revokeDeviceTokenStmt != nil {
		if cerr := q.revokeDeviceTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeDeviceTokenStmt: %w", cerr)
		}
	}
	if q.updateDeviceTokensStmt != nil {
		if cerr := q.updateDeviceTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeviceTokensStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	authorizeDeviceCodeStmt          *sql.Stmt
	createDeviceCodeStmt             *sql.Stmt
	createDeviceTokenStmt            *sql.Stmt
	deleteExpiredDeviceCodesStmt     *sql.Stmt
	getDeviceCodeByDeviceCodeStmt    *sql.Stmt
	getDeviceCodeByUserCodeStmt      *sql.Stmt
	getDeviceTokenByAccessTokenStmt  *sql.Stmt
	getDeviceTokenByRefreshTokenStmt *sql.Stmt
	markDeviceCodeAsUsedStmt         *sql.Stmt
	revokeAllDeviceTokensForUserStmt *sql.Stmt
	revokeDeviceTokenStmt            *sql.Stmt
	updateDeviceTokensStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		authorizeDeviceCodeStmt:          q.authorizeDeviceCodeStmt,
		createDeviceCodeStmt:             q.createDeviceCodeStmt,
		createDeviceTokenStmt:            q.createDeviceTokenStmt,
		deleteExpiredDeviceCodesStmt:     q.deleteExpiredDeviceCodesStmt,
		getDeviceCodeByDeviceCodeStmt:    q.getDeviceCodeByDeviceCodeStmt,
		getDeviceCodeByUserCodeStmt:      q.getDeviceCodeByUserCodeStmt,
		getDeviceTokenByAccessTokenStmt:  q.getDeviceTokenByAccessTokenStmt,
		getDeviceTokenByRefreshTokenStmt: q.getDeviceTokenByRefreshTokenStmt,
		markDeviceCodeAsUsedStmt:         q.markDeviceCodeAsUsedStmt,
		revokeAllDeviceTokensForUserStmt: q.revokeAllDeviceTokensForUserStmt,
		revokeDeviceTokenStmt:            q.revokeDeviceTokenStmt,
		updateDeviceTokensStmt:           q.updateDeviceTokensStmt,
	}
}
