// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_token.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDeviceToken = `-- name: CreateDeviceToken :exec
INSERT INTO device_tokens (id, access_token, refresh_token, organization_id, user_id, device_name, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateDeviceTokenParams struct {
	ID             uuid.UUID      `json:"id"`
	AccessToken    string         `json:"access_token"`
	RefreshToken   string         `json:"refresh_token"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	UserID         uuid.UUID      `json:"user_id"`
	DeviceName     sql.NullString `json:"device_name"`
	ExpiresAt      time.Time      `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) error {
	_, err := q.exec(ctx, q.createDeviceTokenStmt, createDeviceToken,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.OrganizationID,
		arg.UserID,
		arg.DeviceName,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const getDeviceTokenByAccessToken = `-- name: GetDeviceTokenByAccessToken :one
SELECT id, access_token, refresh_token, organization_id, user_id, device_name, expires_at, created_at, revoked_at
FROM device_tokens
WHERE access_token = $1
`

func (q *Queries) GetDeviceTokenByAccessToken(ctx context.Context, accessToken string) (DeviceToken, error) {
	row := q.queryRow(ctx, q.getDeviceTokenByAccessTokenStmt, getDeviceTokenByAccessToken, accessToken)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.OrganizationID,
		&i.UserID,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeviceTokenByRefreshToken = `-- name: GetDeviceTokenByRefreshToken :one
SELECT id, access_token, refresh_token, organization_id, user_id, device_name, expires_at, created_at, revoked_at
FROM device_tokens
WHERE refresh_token = $1
`

func (q *Queries) GetDeviceTokenByRefreshToken(ctx context.Context, refreshToken string) (DeviceToken, error) {
	row := q.queryRow(ctx, q.getDeviceTokenByRefreshTokenStmt, getDeviceTokenByRefreshToken, refreshToken)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.OrganizationID,
		&i.UserID,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllDeviceTokensForUser = `-- name: RevokeAllDeviceTokensForUser :exec
UPDATE device_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllDeviceTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.revokeAllDeviceTokensForUserStmt, revokeAllDeviceTokensForUser, userID)
	return err
}

const revokeDeviceToken = `-- name: RevokeDeviceToken :exec
UPDATE device_tokens
SET revoked_at = NOW()
WHERE access_token = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeDeviceToken(ctx context.Context, accessToken string) error {
	_, err := q.exec(ctx, q.revokeDeviceTokenStmt, revokeDeviceToken, accessToken)
	return err
}

const updateDeviceTokens = `-- name: UpdateDeviceTokens :exec
UPDATE device_tokens
SET access_token = $2, refresh_token = $3, expires_at = $4
WHERE refresh_token = $1 AND revoked_at IS NULL
`

type UpdateDeviceTokensParams struct {
	RefreshToken   string    `json:"refresh_token"`
	AccessToken    string    `json:"access_token"`
	RefreshToken_2 string    `json:"refresh_token_2"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) UpdateDeviceTokens(ctx context.Context, arg UpdateDeviceTokensParams) error {
	_, err := q.exec(ctx, q.updateDeviceTokensStmt, updateDeviceTokens,
		arg.RefreshToken,
		arg.AccessToken,
		arg.RefreshToken_2,
		arg.ExpiresAt,
	)
	return err
}
