// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: device_code.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const authorizeDeviceCode = `-- name: AuthorizeDeviceCode :exec
UPDATE device_codes
SET status = 'authorized', organization_id = $2, user_id = $3
WHERE user_code = $1 AND status = 'pending'
`

type AuthorizeDeviceCodeParams struct {
	UserCode       string        `json:"user_code"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
	UserID         uuid.NullUUID `json:"user_id"`
}

func (q *Queries) AuthorizeDeviceCode(ctx context.Context, arg AuthorizeDeviceCodeParams) error {
	_, err := q.exec(ctx, q.authorizeDeviceCodeStmt, authorizeDeviceCode, arg.UserCode, arg.OrganizationID, arg.UserID)
	return err
}

const createDeviceCode = `-- name: CreateDeviceCode :exec
INSERT INTO device_codes (id, device_code, user_code, status, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDeviceCodeParams struct {
	ID         uuid.UUID `json:"id"`
	DeviceCode string    `json:"device_code"`
	UserCode   string    `json:"user_code"`
	Status     string    `json:"status"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateDeviceCode(ctx context.Context, arg CreateDeviceCodeParams) error {
	_, err := q.exec(ctx, q.createDeviceCodeStmt, createDeviceCode,
		arg.ID,
		arg.DeviceCode,
		arg.UserCode,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredDeviceCodes = `-- name: DeleteExpiredDeviceCodes :exec
DELETE FROM device_codes
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredDeviceCodes(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredDeviceCodesStmt, deleteExpiredDeviceCodes)
	return err
}

const getDeviceCodeByDeviceCode = `-- name: GetDeviceCodeByDeviceCode :one
SELECT id, device_code, user_code, status, organization_id, user_id, expires_at, created_at
FROM device_codes
WHERE device_code = $1
`

func (q *Queries) GetDeviceCodeByDeviceCode(ctx context.Context, deviceCode string) (DeviceCode, error) {
	row := q.queryRow(ctx, q.getDeviceCodeByDeviceCodeStmt, getDeviceCodeByDeviceCode, deviceCode)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.OrganizationID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceCodeByUserCode = `-- name: GetDeviceCodeByUserCode :one
SELECT id, device_code, user_code, status, organization_id, user_id, expires_at, created_at
FROM device_codes
WHERE user_code = $1
`

func (q *Queries) GetDeviceCodeByUserCode(ctx context.Context, userCode string) (DeviceCode, error) {
	row := q.queryRow(ctx, q.getDeviceCodeByUserCodeStmt, getDeviceCodeByUserCode, userCode)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.OrganizationID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markDeviceCodeAsUsed = `-- name: MarkDeviceCodeAsUsed :exec
UPDATE device_codes
SET status = 'used'
WHERE device_code = $1 AND status = 'authorized'
`

func (q *Queries) MarkDeviceCodeAsUsed(ctx context.Context, deviceCode string) error {
	_, err := q.exec(ctx, q.markDeviceCodeAsUsedStmt, markDeviceCodeAsUsed, deviceCode)
	return err
}
