// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type DeviceCode struct {
	ID             uuid.UUID     `json:"id"`
	DeviceCode     string        `json:"device_code"`
	UserCode       string        `json:"user_code"`
	Status         string        `json:"status"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
	UserID         uuid.NullUUID `json:"user_id"`
	ExpiresAt      time.Time     `json:"expires_at"`
	CreatedAt      time.Time     `json:"created_at"`
}

type DeviceToken struct {
	ID             uuid.UUID      `json:"id"`
	AccessToken    string         `json:"access_token"`
	RefreshToken   string         `json:"refresh_token"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	UserID         uuid.UUID      `json:"user_id"`
	DeviceName     sql.NullString `json:"device_name"`
	ExpiresAt      time.Time      `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	RevokedAt      sql.NullTime   `json:"revoked_at"`
}
