// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AuthorizeDeviceCode(ctx context.Context, arg AuthorizeDeviceCodeParams) error
	CreateDeviceCode(ctx context.Context, arg CreateDeviceCodeParams) error
	CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) error
	DeleteExpiredDeviceCodes(ctx context.Context) error
	GetDeviceCodeByDeviceCode(ctx context.Context, deviceCode string) (DeviceCode, error)
	GetDeviceCodeByUserCode(ctx context.Context, userCode string) (DeviceCode, error)
	GetDeviceTokenByAccessToken(ctx context.Context, accessToken string) (DeviceToken, error)
	GetDeviceTokenByRefreshToken(ctx context.Context, refreshToken string) (DeviceToken, error)
	MarkDeviceCodeAsUsed(ctx context.Context, deviceCode string) error
	RevokeAllDeviceTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeDeviceToken(ctx context.Context, accessToken string) error
	UpdateDeviceTokens(ctx context.Context, arg UpdateDeviceTokensParams) error
}

var _ Querier = (*Queries)(nil)
