// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.bulkDeleteGitHubRepositoriesStmt, err = db.PrepareContext(ctx, bulkDeleteGitHubRepositories); err != nil {
		return nil, fmt.Errorf("error preparing query BulkDeleteGitHubRepositories: %w", err)
	}
	if q.deleteCredentialStmt, err = db.PrepareContext(ctx, deleteCredential); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCredential: %w", err)
	}
	if q.deleteExpiredUnclaimedInstallationsStmt, err = db.PrepareContext(ctx, deleteExpiredUnclaimedInstallations); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredUnclaimedInstallations: %w", err)
	}
	if q.deleteGitHubRepositoryByGitHubIDStmt, err = db.PrepareContext(ctx, deleteGitHubRepositoryByGitHubID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteGitHubRepositoryByGitHubID: %w", err)
	}
	if q.deleteIntegrationStmt, err = db.PrepareContext(ctx, deleteIntegration); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIntegration: %w", err)
	}
	if q.deleteUnclaimedInstallationStmt, err = db.PrepareContext(ctx, deleteUnclaimedInstallation); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUnclaimedInstallation: %w", err)
	}
	if q.findCredentialByIntegrationStmt, err = db.PrepareContext(ctx, findCredentialByIntegration); err != nil {
		return nil, fmt.Errorf("error preparing query FindCredentialByIntegration: %w", err)
	}
	if q.findExpiringCredentialsStmt, err = db.PrepareContext(ctx, findExpiringCredentials); err != nil {
		return nil, fmt.Errorf("error preparing query FindExpiringCredentials: %w", err)
	}
	if q.findGitHubRepositoriesByIntegrationIDStmt, err = db.PrepareContext(ctx, findGitHubRepositoriesByIntegrationID); err != nil {
		return nil, fmt.Errorf("error preparing query FindGitHubRepositoriesByIntegrationID: %w", err)
	}
	if q.findGitHubRepositoryByGitHubIDStmt, err = db.PrepareContext(ctx, findGitHubRepositoryByGitHubID); err != nil {
		return nil, fmt.Errorf("error preparing query FindGitHubRepositoryByGitHubID: %w", err)
	}
	if q.findIntegrationByBotIDAndTypeStmt, err = db.PrepareContext(ctx, findIntegrationByBotIDAndType); err != nil {
		return nil, fmt.Errorf("error preparing query FindIntegrationByBotIDAndType: %w", err)
	}
	if q.findIntegrationByIDStmt, err = db.PrepareContext(ctx, findIntegrationByID); err != nil {
		return nil, fmt.Errorf("error preparing query FindIntegrationByID: %w", err)
	}
	if q.findIntegrationsByOrganizationStmt, err = db.PrepareContext(ctx, findIntegrationsByOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query FindIntegrationsByOrganization: %w", err)
	}
	if q.findIntegrationsByOrganizationAndTypeStmt, err = db.PrepareContext(ctx, findIntegrationsByOrganizationAndType); err != nil {
		return nil, fmt.Errorf("error preparing query FindIntegrationsByOrganizationAndType: %w", err)
	}
	if q.findUnclaimedInstallationByInstallationIDStmt, err = db.PrepareContext(ctx, findUnclaimedInstallationByInstallationID); err != nil {
		return nil, fmt.Errorf("error preparing query FindUnclaimedInstallationByInstallationID: %w", err)
	}
	if q.findUnclaimedInstallationsStmt, err = db.PrepareContext(ctx, findUnclaimedInstallations); err != nil {
		return nil, fmt.Errorf("error preparing query FindUnclaimedInstallations: %w", err)
	}
	if q.markUnclaimedInstallationAsClaimedStmt, err = db.PrepareContext(ctx, markUnclaimedInstallationAsClaimed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkUnclaimedInstallationAsClaimed: %w", err)
	}
	if q.storeCredentialStmt, err = db.PrepareContext(ctx, storeCredential); err != nil {
		return nil, fmt.Errorf("error preparing query StoreCredential: %w", err)
	}
	if q.storeIntegrationStmt, err = db.PrepareContext(ctx, storeIntegration); err != nil {
		return nil, fmt.Errorf("error preparing query StoreIntegration: %w", err)
	}
	if q.storeUnclaimedInstallationStmt, err = db.PrepareContext(ctx, storeUnclaimedInstallation); err != nil {
		return nil, fmt.Errorf("error preparing query StoreUnclaimedInstallation: %w", err)
	}
	if q.updateCredentialStmt, err = db.PrepareContext(ctx, updateCredential); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCredential: %w", err)
	}
	if q.updateGitHubRepositoryLastSyncTimeStmt, err = db.PrepareContext(ctx, updateGitHubRepositoryLastSyncTime); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGitHubRepositoryLastSyncTime: %w", err)
	}
	if q.updateGitHubRepositoryPermissionsStmt, err = db.PrepareContext(ctx, updateGitHubRepositoryPermissions); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGitHubRepositoryPermissions: %w", err)
	}
	if q.updateIntegrationLastUsedStmt, err = db.PrepareContext(ctx, updateIntegrationLastUsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateIntegrationLastUsed: %w", err)
	}
	if q.updateIntegrationStatusStmt, err = db.PrepareContext(ctx, updateIntegrationStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateIntegrationStatus: %w", err)
	}
	if q.upsertGitHubRepositoryStmt, err = db.PrepareContext(ctx, upsertGitHubRepository); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertGitHubRepository: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.bulkDeleteGitHubRepositoriesStmt != nil {
		if cerr := q.bulkDeleteGitHubRepositoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing bulkDeleteGitHubRepositoriesStmt: %w", cerr)
		}
	}
	if q.deleteCredentialStmt != nil {
		if cerr := q.deleteCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCredentialStmt: %w", cerr)
		}
	}
	if q.deleteExpiredUnclaimedInstallationsStmt != nil {
		if cerr := q.deleteExpiredUnclaimedInstallationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredUnclaimedInstallationsStmt: %w", cerr)
		}
	}
	if q.deleteGitHubRepositoryByGitHubIDStmt != nil {
		if cerr := q.deleteGitHubRepositoryByGitHubIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteGitHubRepositoryByGitHubIDStmt: %w", cerr)
		}
	}
	if q.deleteIntegrationStmt != nil {
		if cerr := q.deleteIntegrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteIntegrationStmt: %w", cerr)
		}
	}
	if q.deleteUnclaimedInstallationStmt != nil {
		if cerr := q.deleteUnclaimedInstallationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUnclaimedInstallationStmt: %w", cerr)
		}
	}
	if q.findCredentialByIntegrationStmt != nil {
		if cerr := q.findCredentialByIntegrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findCredentialByIntegrationStmt: %w", cerr)
		}
	}
	if q.findExpiringCredentialsStmt != nil {
		if cerr := q.findExpiringCredentialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findExpiringCredentialsStmt: %w", cerr)
		}
	}
	if q.findGitHubRepositoriesByIntegrationIDStmt != nil {
		if cerr := q.findGitHubRepositoriesByIntegrationIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findGitHubRepositoriesByIntegrationIDStmt: %w", cerr)
		}
	}
	if q.findGitHubRepositoryByGitHubIDStmt != nil {
		if cerr := q.findGitHubRepositoryByGitHubIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findGitHubRepositoryByGitHubIDStmt: %w", cerr)
		}
	}
	if q.findIntegrationByBotIDAndTypeStmt != nil {
		if cerr := q.findIntegrationByBotIDAndTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findIntegrationByBotIDAndTypeStmt: %w", cerr)
		}
	}
	if q.findIntegrationByIDStmt != nil {
		if cerr := q.findIntegrationByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findIntegrationByIDStmt: %w", cerr)
		}
	}
	if q.findIntegrationsByOrganizationStmt != nil {
		if cerr := q.findIntegrationsByOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findIntegrationsByOrganizationStmt: %w", cerr)
		}
	}
	if q.findIntegrationsByOrganizationAndTypeStmt != nil {
		if cerr := q.findIntegrationsByOrganizationAndTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findIntegrationsByOrganizationAndTypeStmt: %w", cerr)
		}
	}
	if q.findUnclaimedInstallationByInstallationIDStmt != nil {
		if cerr := q.findUnclaimedInstallationByInstallationIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findUnclaimedInstallationByInstallationIDStmt: %w", cerr)
		}
	}
	if q.findUnclaimedInstallationsStmt != nil {
		if cerr := q.findUnclaimedInstallationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findUnclaimedInstallationsStmt: %w", cerr)
		}
	}
	if q.markUnclaimedInstallationAsClaimedStmt != nil {
		if cerr := q.markUnclaimedInstallationAsClaimedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markUnclaimedInstallationAsClaimedStmt: %w", cerr)
		}
	}
	if q.storeCredentialStmt != nil {
		if cerr := q.storeCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing storeCredentialStmt: %w", cerr)
		}
	}
	if q.storeIntegrationStmt != nil {
		if cerr := q.storeIntegrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing storeIntegrationStmt: %w", cerr)
		}
	}
	if q.storeUnclaimedInstallationStmt != nil {
		if cerr := q.storeUnclaimedInstallationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing storeUnclaimedInstallationStmt: %w", cerr)
		}
	}
	if q.updateCredentialStmt != nil {
		if cerr := q.updateCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCredentialStmt: %w", cerr)
		}
	}
	if q.updateGitHubRepositoryLastSyncTimeStmt != nil {
		if cerr := q.updateGitHubRepositoryLastSyncTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGitHubRepositoryLastSyncTimeStmt: %w", cerr)
		}
	}
	if q.updateGitHubRepositoryPermissionsStmt != nil {
		if cerr := q.updateGitHubRepositoryPermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGitHubRepositoryPermissionsStmt: %w", cerr)
		}
	}
	if q.updateIntegrationLastUsedStmt != nil {
		if cerr := q.updateIntegrationLastUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateIntegrationLastUsedStmt: %w", cerr)
		}
	}
	if q.updateIntegrationStatusStmt != nil {
		if cerr := q.updateIntegrationStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateIntegrationStatusStmt: %w", cerr)
		}
	}
	if q.upsertGitHubRepositoryStmt != nil {
		if cerr := q.upsertGitHubRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertGitHubRepositoryStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                            DBTX
	tx                                            *sql.Tx
	bulkDeleteGitHubRepositoriesStmt              *sql.Stmt
	deleteCredentialStmt                          *sql.Stmt
	deleteExpiredUnclaimedInstallationsStmt       *sql.Stmt
	deleteGitHubRepositoryByGitHubIDStmt          *sql.Stmt
	deleteIntegrationStmt                         *sql.Stmt
	deleteUnclaimedInstallationStmt               *sql.Stmt
	findCredentialByIntegrationStmt               *sql.Stmt
	findExpiringCredentialsStmt                   *sql.Stmt
	findGitHubRepositoriesByIntegrationIDStmt     *sql.Stmt
	findGitHubRepositoryByGitHubIDStmt            *sql.Stmt
	findIntegrationByBotIDAndTypeStmt             *sql.Stmt
	findIntegrationByIDStmt                       *sql.Stmt
	findIntegrationsByOrganizationStmt            *sql.Stmt
	findIntegrationsByOrganizationAndTypeStmt     *sql.Stmt
	findUnclaimedInstallationByInstallationIDStmt *sql.Stmt
	findUnclaimedInstallationsStmt                *sql.Stmt
	markUnclaimedInstallationAsClaimedStmt        *sql.Stmt
	storeCredentialStmt                           *sql.Stmt
	storeIntegrationStmt                          *sql.Stmt
	storeUnclaimedInstallationStmt                *sql.Stmt
	updateCredentialStmt                          *sql.Stmt
	updateGitHubRepositoryLastSyncTimeStmt        *sql.Stmt
	updateGitHubRepositoryPermissionsStmt         *sql.Stmt
	updateIntegrationLastUsedStmt                 *sql.Stmt
	updateIntegrationStatusStmt                   *sql.Stmt
	upsertGitHubRepositoryStmt                    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                            tx,
		tx:                                            tx,
		bulkDeleteGitHubRepositoriesStmt:              q.bulkDeleteGitHubRepositoriesStmt,
		deleteCredentialStmt:                          q.deleteCredentialStmt,
		deleteExpiredUnclaimedInstallationsStmt:       q.deleteExpiredUnclaimedInstallationsStmt,
		deleteGitHubRepositoryByGitHubIDStmt:          q.deleteGitHubRepositoryByGitHubIDStmt,
		deleteIntegrationStmt:                         q.deleteIntegrationStmt,
		deleteUnclaimedInstallationStmt:               q.deleteUnclaimedInstallationStmt,
		findCredentialByIntegrationStmt:               q.findCredentialByIntegrationStmt,
		findExpiringCredentialsStmt:                   q.findExpiringCredentialsStmt,
		findGitHubRepositoriesByIntegrationIDStmt:     q.findGitHubRepositoriesByIntegrationIDStmt,
		findGitHubRepositoryByGitHubIDStmt:            q.findGitHubRepositoryByGitHubIDStmt,
		findIntegrationByBotIDAndTypeStmt:             q.findIntegrationByBotIDAndTypeStmt,
		findIntegrationByIDStmt:                       q.findIntegrationByIDStmt,
		findIntegrationsByOrganizationStmt:            q.findIntegrationsByOrganizationStmt,
		findIntegrationsByOrganizationAndTypeStmt:     q.findIntegrationsByOrganizationAndTypeStmt,
		findUnclaimedInstallationByInstallationIDStmt: q.findUnclaimedInstallationByInstallationIDStmt,
		findUnclaimedInstallationsStmt:                q.findUnclaimedInstallationsStmt,
		markUnclaimedInstallationAsClaimedStmt:        q.markUnclaimedInstallationAsClaimedStmt,
		storeCredentialStmt:                           q.storeCredentialStmt,
		storeIntegrationStmt:                          q.storeIntegrationStmt,
		storeUnclaimedInstallationStmt:                q.storeUnclaimedInstallationStmt,
		updateCredentialStmt:                          q.updateCredentialStmt,
		updateGitHubRepositoryLastSyncTimeStmt:        q.updateGitHubRepositoryLastSyncTimeStmt,
		updateGitHubRepositoryPermissionsStmt:         q.updateGitHubRepositoryPermissionsStmt,
		updateIntegrationLastUsedStmt:                 q.updateIntegrationLastUsedStmt,
		updateIntegrationStatusStmt:                   q.updateIntegrationStatusStmt,
		upsertGitHubRepositoryStmt:                    q.upsertGitHubRepositoryStmt,
	}
}
