// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Integration struct {
	ID                      uuid.UUID             `json:"id"`
	OrganizationID          uuid.UUID             `json:"organization_id"`
	UserID                  uuid.UUID             `json:"user_id"`
	ConnectorType           string                `json:"connector_type"`
	Status                  string                `json:"status"`
	BotID                   sql.NullString        `json:"bot_id"`
	ConnectorUserID         sql.NullString        `json:"connector_user_id"`
	ConnectorOrganizationID sql.NullString        `json:"connector_organization_id"`
	Metadata                pqtype.NullRawMessage `json:"metadata"`
	CreatedAt               time.Time             `json:"created_at"`
	UpdatedAt               time.Time             `json:"updated_at"`
	LastUsedAt              sql.NullTime          `json:"last_used_at"`
}

type IntegrationCredential struct {
	ID                      uuid.UUID    `json:"id"`
	IntegrationID           uuid.UUID    `json:"integration_id"`
	CredentialType          string       `json:"credential_type"`
	CredentialDataEncrypted string       `json:"credential_data_encrypted"`
	ExpiresAt               sql.NullTime `json:"expires_at"`
	EncryptionKeyID         string       `json:"encryption_key_id"`
	CreatedAt               time.Time    `json:"created_at"`
	UpdatedAt               time.Time    `json:"updated_at"`
}
