// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteCredential(ctx context.Context, integrationID uuid.UUID) error
	DeleteIntegration(ctx context.Context, id uuid.UUID) error
	FindCredentialByIntegration(ctx context.Context, integrationID uuid.UUID) (IntegrationCredential, error)
	FindExpiringCredentials(ctx context.Context, expiresAt sql.NullTime) ([]IntegrationCredential, error)
	FindIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error)
	FindIntegrationsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Integration, error)
	FindIntegrationsByOrganizationAndType(ctx context.Context, arg FindIntegrationsByOrganizationAndTypeParams) ([]Integration, error)
	StoreCredential(ctx context.Context, arg StoreCredentialParams) error
	StoreIntegration(ctx context.Context, arg StoreIntegrationParams) error
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdateIntegrationLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateIntegrationStatus(ctx context.Context, arg UpdateIntegrationStatusParams) error
}

var _ Querier = (*Queries)(nil)
