// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	BulkDeleteGitHubRepositories(ctx context.Context, arg BulkDeleteGitHubRepositoriesParams) error
	DeleteCredential(ctx context.Context, integrationID uuid.UUID) error
	DeleteExpiredUnclaimedInstallations(ctx context.Context) error
	DeleteGitHubRepositoryByGitHubID(ctx context.Context, arg DeleteGitHubRepositoryByGitHubIDParams) error
	DeleteIntegration(ctx context.Context, id uuid.UUID) error
	DeleteUnclaimedInstallation(ctx context.Context, githubInstallationID string) error
	FindCredentialByIntegration(ctx context.Context, integrationID uuid.UUID) (IntegrationCredential, error)
	FindExpiringCredentials(ctx context.Context, expiresAt sql.NullTime) ([]IntegrationCredential, error)
	FindGitHubRepositoriesByIntegrationID(ctx context.Context, integrationID uuid.UUID) ([]GithubRepository, error)
	FindGitHubRepositoryByGitHubID(ctx context.Context, arg FindGitHubRepositoryByGitHubIDParams) (GithubRepository, error)
	FindIntegrationByBotIDAndType(ctx context.Context, arg FindIntegrationByBotIDAndTypeParams) (Integration, error)
	FindIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error)
	FindIntegrationsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Integration, error)
	FindIntegrationsByOrganizationAndType(ctx context.Context, arg FindIntegrationsByOrganizationAndTypeParams) ([]Integration, error)
	FindUnclaimedInstallationByInstallationID(ctx context.Context, githubInstallationID string) (UnclaimedInstallation, error)
	FindUnclaimedInstallations(ctx context.Context, limit int32) ([]UnclaimedInstallation, error)
	MarkUnclaimedInstallationAsClaimed(ctx context.Context, arg MarkUnclaimedInstallationAsClaimedParams) error
	StoreCredential(ctx context.Context, arg StoreCredentialParams) error
	StoreIntegration(ctx context.Context, arg StoreIntegrationParams) error
	// Unclaimed Installation Queries
	StoreUnclaimedInstallation(ctx context.Context, arg StoreUnclaimedInstallationParams) error
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdateGitHubRepositoryLastSyncTime(ctx context.Context, arg UpdateGitHubRepositoryLastSyncTimeParams) error
	UpdateGitHubRepositoryPermissions(ctx context.Context, arg UpdateGitHubRepositoryPermissionsParams) error
	UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) error
	UpdateIntegrationLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateIntegrationMetadata(ctx context.Context, arg UpdateIntegrationMetadataParams) error
	UpdateIntegrationStatus(ctx context.Context, arg UpdateIntegrationStatusParams) error
	// GitHub Repository Queries
	UpsertGitHubRepository(ctx context.Context, arg UpsertGitHubRepositoryParams) error
}

var _ Querier = (*Queries)(nil)
