// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: unclaimed_installation.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const deleteExpiredUnclaimedInstallations = `-- name: DeleteExpiredUnclaimedInstallations :exec
DELETE FROM unclaimed_installations 
WHERE expires_at < NOW() AND claimed_at IS NULL
`

func (q *Queries) DeleteExpiredUnclaimedInstallations(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredUnclaimedInstallationsStmt, deleteExpiredUnclaimedInstallations)
	return err
}

const deleteUnclaimedInstallation = `-- name: DeleteUnclaimedInstallation :exec
DELETE FROM unclaimed_installations 
WHERE github_installation_id = $1
`

func (q *Queries) DeleteUnclaimedInstallation(ctx context.Context, githubInstallationID int64) error {
	_, err := q.exec(ctx, q.deleteUnclaimedInstallationStmt, deleteUnclaimedInstallation, githubInstallationID)
	return err
}

const findUnclaimedInstallationByInstallationID = `-- name: FindUnclaimedInstallationByInstallationID :one
SELECT id, github_installation_id, github_app_id, github_account_id,
    github_account_login, github_account_type, repository_selection,
    permissions, events, access_tokens_url, repositories_url, html_url,
    app_slug, suspended_at, suspended_by, webhook_sender, raw_webhook_payload,
    created_at, github_created_at, github_updated_at, expires_at,
    claimed_at, claimed_by_organization_id, claimed_by_user_id
FROM unclaimed_installations 
WHERE github_installation_id = $1
`

func (q *Queries) FindUnclaimedInstallationByInstallationID(ctx context.Context, githubInstallationID int64) (UnclaimedInstallation, error) {
	row := q.queryRow(ctx, q.findUnclaimedInstallationByInstallationIDStmt, findUnclaimedInstallationByInstallationID, githubInstallationID)
	var i UnclaimedInstallation
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.GithubAppID,
		&i.GithubAccountID,
		&i.GithubAccountLogin,
		&i.GithubAccountType,
		&i.RepositorySelection,
		&i.Permissions,
		pq.Array(&i.Events),
		&i.AccessTokensUrl,
		&i.RepositoriesUrl,
		&i.HtmlUrl,
		&i.AppSlug,
		&i.SuspendedAt,
		&i.SuspendedBy,
		&i.WebhookSender,
		&i.RawWebhookPayload,
		&i.CreatedAt,
		&i.GithubCreatedAt,
		&i.GithubUpdatedAt,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.ClaimedByOrganizationID,
		&i.ClaimedByUserID,
	)
	return i, err
}

const findUnclaimedInstallations = `-- name: FindUnclaimedInstallations :many
SELECT id, github_installation_id, github_app_id, github_account_id,
    github_account_login, github_account_type, repository_selection,
    permissions, events, access_tokens_url, repositories_url, html_url,
    app_slug, suspended_at, suspended_by, webhook_sender, raw_webhook_payload,
    created_at, github_created_at, github_updated_at, expires_at,
    claimed_at, claimed_by_organization_id, claimed_by_user_id
FROM unclaimed_installations 
WHERE claimed_at IS NULL 
ORDER BY created_at DESC 
LIMIT $1
`

func (q *Queries) FindUnclaimedInstallations(ctx context.Context, limit int32) ([]UnclaimedInstallation, error) {
	rows, err := q.query(ctx, q.findUnclaimedInstallationsStmt, findUnclaimedInstallations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnclaimedInstallation
	for rows.Next() {
		var i UnclaimedInstallation
		if err := rows.Scan(
			&i.ID,
			&i.GithubInstallationID,
			&i.GithubAppID,
			&i.GithubAccountID,
			&i.GithubAccountLogin,
			&i.GithubAccountType,
			&i.RepositorySelection,
			&i.Permissions,
			pq.Array(&i.Events),
			&i.AccessTokensUrl,
			&i.RepositoriesUrl,
			&i.HtmlUrl,
			&i.AppSlug,
			&i.SuspendedAt,
			&i.SuspendedBy,
			&i.WebhookSender,
			&i.RawWebhookPayload,
			&i.CreatedAt,
			&i.GithubCreatedAt,
			&i.GithubUpdatedAt,
			&i.ExpiresAt,
			&i.ClaimedAt,
			&i.ClaimedByOrganizationID,
			&i.ClaimedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnclaimedInstallationAsClaimed = `-- name: MarkUnclaimedInstallationAsClaimed :exec
UPDATE unclaimed_installations 
SET claimed_at = NOW(), 
    claimed_by_organization_id = $1, 
    claimed_by_user_id = $2
WHERE github_installation_id = $3
`

type MarkUnclaimedInstallationAsClaimedParams struct {
	ClaimedByOrganizationID uuid.NullUUID `json:"claimed_by_organization_id"`
	ClaimedByUserID         uuid.NullUUID `json:"claimed_by_user_id"`
	GithubInstallationID    int64         `json:"github_installation_id"`
}

func (q *Queries) MarkUnclaimedInstallationAsClaimed(ctx context.Context, arg MarkUnclaimedInstallationAsClaimedParams) error {
	_, err := q.exec(ctx, q.markUnclaimedInstallationAsClaimedStmt, markUnclaimedInstallationAsClaimed, arg.ClaimedByOrganizationID, arg.ClaimedByUserID, arg.GithubInstallationID)
	return err
}

const storeUnclaimedInstallation = `-- name: StoreUnclaimedInstallation :exec

INSERT INTO unclaimed_installations (
    id, github_installation_id, github_app_id, github_account_id,
    github_account_login, github_account_type, repository_selection,
    permissions, events, access_tokens_url, repositories_url, html_url,
    app_slug, suspended_at, suspended_by, webhook_sender, raw_webhook_payload,
    created_at, github_created_at, github_updated_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
`

type StoreUnclaimedInstallationParams struct {
	ID                   uuid.UUID             `json:"id"`
	GithubInstallationID int64                 `json:"github_installation_id"`
	GithubAppID          int64                 `json:"github_app_id"`
	GithubAccountID      int64                 `json:"github_account_id"`
	GithubAccountLogin   string                `json:"github_account_login"`
	GithubAccountType    string                `json:"github_account_type"`
	RepositorySelection  string                `json:"repository_selection"`
	Permissions          json.RawMessage       `json:"permissions"`
	Events               []string              `json:"events"`
	AccessTokensUrl      sql.NullString        `json:"access_tokens_url"`
	RepositoriesUrl      sql.NullString        `json:"repositories_url"`
	HtmlUrl              sql.NullString        `json:"html_url"`
	AppSlug              sql.NullString        `json:"app_slug"`
	SuspendedAt          sql.NullTime          `json:"suspended_at"`
	SuspendedBy          pqtype.NullRawMessage `json:"suspended_by"`
	WebhookSender        pqtype.NullRawMessage `json:"webhook_sender"`
	RawWebhookPayload    pqtype.NullRawMessage `json:"raw_webhook_payload"`
	CreatedAt            time.Time             `json:"created_at"`
	GithubCreatedAt      time.Time             `json:"github_created_at"`
	GithubUpdatedAt      time.Time             `json:"github_updated_at"`
	ExpiresAt            time.Time             `json:"expires_at"`
}

// Unclaimed Installation Queries
func (q *Queries) StoreUnclaimedInstallation(ctx context.Context, arg StoreUnclaimedInstallationParams) error {
	_, err := q.exec(ctx, q.storeUnclaimedInstallationStmt, storeUnclaimedInstallation,
		arg.ID,
		arg.GithubInstallationID,
		arg.GithubAppID,
		arg.GithubAccountID,
		arg.GithubAccountLogin,
		arg.GithubAccountType,
		arg.RepositorySelection,
		arg.Permissions,
		pq.Array(arg.Events),
		arg.AccessTokensUrl,
		arg.RepositoriesUrl,
		arg.HtmlUrl,
		arg.AppSlug,
		arg.SuspendedAt,
		arg.SuspendedBy,
		arg.WebhookSender,
		arg.RawWebhookPayload,
		arg.CreatedAt,
		arg.GithubCreatedAt,
		arg.GithubUpdatedAt,
		arg.ExpiresAt,
	)
	return err
}
