// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateResetPassword(ctx context.Context, arg CreateResetPasswordParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateStateToken(ctx context.Context, arg CreateStateTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	Device(ctx context.Context, deviceID uuid.UUID) (Device, error)
	DevicesByUserID(ctx context.Context, userID uuid.UUID) ([]Device, error)
	EmailVerification(ctx context.Context, verificationID uuid.UUID) (EmailVerificationRow, error)
	MarkEmailVerificationAsExpired(ctx context.Context, verificationID uuid.UUID) error
	MarkResetPasswordAsExpired(ctx context.Context, resetID uuid.UUID) error
	RefreshToken(ctx context.Context, tokenID uuid.UUID) (RefreshToken, error)
	ResetPassword(ctx context.Context, resetID uuid.UUID) (ResetPasswordRow, error)
	RevokeRefreshToken(ctx context.Context, tokenID uuid.UUID) error
	RevokeStateToken(ctx context.Context, token string) error
	SetNewPassword(ctx context.Context, arg SetNewPasswordParams) error
	StateToken(ctx context.Context, token string) (GoogleStateToken, error)
	UserByEmail(ctx context.Context, email string) (UserByEmailRow, error)
	UserByID(ctx context.Context, userID uuid.UUID) (User, error)
	UserSession(ctx context.Context, sessionID uuid.UUID) (UserSession, error)
	UserSessions(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	VerifyEmail(ctx context.Context, userID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
