// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.integrationsStmt, err = db.PrepareContext(ctx, integrations); err != nil {
		return nil, fmt.Errorf("error preparing query integrations: %w", err)
	}
	if q.saveIntegrationStmt, err = db.PrepareContext(ctx, saveIntegration); err != nil {
		return nil, fmt.Errorf("error preparing query saveIntegration: %w", err)
	}
	if q.saveSlackTokenStmt, err = db.PrepareContext(ctx, saveSlackToken); err != nil {
		return nil, fmt.Errorf("error preparing query saveSlackToken: %w", err)
	}
	if q.slackTokenStmt, err = db.PrepareContext(ctx, slackToken); err != nil {
		return nil, fmt.Errorf("error preparing query slackToken: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.integrationsStmt != nil {
		if cerr := q.integrationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing integrationsStmt: %w", cerr)
		}
	}
	if q.saveIntegrationStmt != nil {
		if cerr := q.saveIntegrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveIntegrationStmt: %w", cerr)
		}
	}
	if q.saveSlackTokenStmt != nil {
		if cerr := q.saveSlackTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveSlackTokenStmt: %w", cerr)
		}
	}
	if q.slackTokenStmt != nil {
		if cerr := q.slackTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing slackTokenStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                  DBTX
	tx                  *sql.Tx
	integrationsStmt    *sql.Stmt
	saveIntegrationStmt *sql.Stmt
	saveSlackTokenStmt  *sql.Stmt
	slackTokenStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                  tx,
		tx:                  tx,
		integrationsStmt:    q.integrationsStmt,
		saveIntegrationStmt: q.saveIntegrationStmt,
		saveSlackTokenStmt:  q.saveSlackTokenStmt,
		slackTokenStmt:      q.slackTokenStmt,
	}
}
