// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Integration struct {
	ID                uuid.UUID `json:"id"`
	Provider          string    `json:"provider"`
	Status            string    `json:"status"`
	BusinessID        uuid.UUID `json:"business_id"`
	ProviderProjectID string    `json:"provider_project_id"`
	Active            bool      `json:"active"`
	CreatedAt         time.Time `json:"created_at"`
}

type SlackToken struct {
	TokenID   uuid.UUID    `json:"token_id"`
	TeamID    string       `json:"team_id"`
	Token     string       `json:"token"`
	Expired   bool         `json:"expired"`
	ExpiredAt sql.NullTime `json:"expired_at"`
	CreatedAt time.Time    `json:"created_at"`
}
