// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	integrations(ctx context.Context, businessID uuid.UUID) ([]Integration, error)
	saveIntegration(ctx context.Context, arg saveIntegrationParams) error
	saveSlackToken(ctx context.Context, arg saveSlackTokenParams) error
	slackToken(ctx context.Context, teamID string) (string, error)
}

var _ Querier = (*Queries)(nil)
