// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const integrations = `-- name: integrations :many
SELECT id, provider, status, business_id, provider_project_id, active, created_at FROM integration WHERE business_id = $1 and active='t'
`

func (q *Queries) integrations(ctx context.Context, businessID uuid.UUID) ([]Integration, error) {
	rows, err := q.query(ctx, q.integrationsStmt, integrations, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Status,
			&i.BusinessID,
			&i.ProviderProjectID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveIntegration = `-- name: saveIntegration :exec
INSERT INTO integration (id, provider, status, business_id, provider_project_id) VALUES ($1, $2, $3, $4, $5)
`

type saveIntegrationParams struct {
	ID                uuid.UUID `json:"id"`
	Provider          string    `json:"provider"`
	Status            string    `json:"status"`
	BusinessID        uuid.UUID `json:"business_id"`
	ProviderProjectID string    `json:"provider_project_id"`
}

func (q *Queries) saveIntegration(ctx context.Context, arg saveIntegrationParams) error {
	_, err := q.exec(ctx, q.saveIntegrationStmt, saveIntegration,
		arg.ID,
		arg.Provider,
		arg.Status,
		arg.BusinessID,
		arg.ProviderProjectID,
	)
	return err
}

const saveSlackToken = `-- name: saveSlackToken :exec
INSERT INTO slack_token (token_id, team_id, token) VALUES ($1, $2, $3)
`

type saveSlackTokenParams struct {
	TokenID uuid.UUID `json:"token_id"`
	TeamID  string    `json:"team_id"`
	Token   string    `json:"token"`
}

func (q *Queries) saveSlackToken(ctx context.Context, arg saveSlackTokenParams) error {
	_, err := q.exec(ctx, q.saveSlackTokenStmt, saveSlackToken, arg.TokenID, arg.TeamID, arg.Token)
	return err
}

const slackToken = `-- name: slackToken :one
SELECT token FROM slack_token WHERE team_id = $1 and expired='f'
`

func (q *Queries) slackToken(ctx context.Context, teamID string) (string, error) {
	row := q.queryRow(ctx, q.slackTokenStmt, slackToken, teamID)
	var token string
	err := row.Scan(&token)
	return token, err
}
