// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: credential.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM integration_credentials
WHERE integration_id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, integrationID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteCredentialStmt, deleteCredential, integrationID)
	return err
}

const findCredentialByIntegration = `-- name: FindCredentialByIntegration :one
SELECT id, integration_id, credential_type, credential_data_encrypted,
       expires_at, encryption_key_id, created_at, updated_at
FROM integration_credentials
WHERE integration_id = $1
`

func (q *Queries) FindCredentialByIntegration(ctx context.Context, integrationID uuid.UUID) (IntegrationCredential, error) {
	row := q.queryRow(ctx, q.findCredentialByIntegrationStmt, findCredentialByIntegration, integrationID)
	var i IntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.CredentialType,
		&i.CredentialDataEncrypted,
		&i.ExpiresAt,
		&i.EncryptionKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findExpiringCredentials = `-- name: FindExpiringCredentials :many
SELECT id, integration_id, credential_type, credential_data_encrypted,
       expires_at, encryption_key_id, created_at, updated_at
FROM integration_credentials
WHERE expires_at IS NOT NULL AND expires_at < $1
ORDER BY expires_at ASC
`

func (q *Queries) FindExpiringCredentials(ctx context.Context, expiresAt sql.NullTime) ([]IntegrationCredential, error) {
	rows, err := q.query(ctx, q.findExpiringCredentialsStmt, findExpiringCredentials, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationCredential
	for rows.Next() {
		var i IntegrationCredential
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.CredentialType,
			&i.CredentialDataEncrypted,
			&i.ExpiresAt,
			&i.EncryptionKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeCredential = `-- name: StoreCredential :exec
INSERT INTO integration_credentials (
    id, integration_id, credential_type, credential_data_encrypted,
    expires_at, encryption_key_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type StoreCredentialParams struct {
	ID                      uuid.UUID    `json:"id"`
	IntegrationID           uuid.UUID    `json:"integration_id"`
	CredentialType          string       `json:"credential_type"`
	CredentialDataEncrypted string       `json:"credential_data_encrypted"`
	ExpiresAt               sql.NullTime `json:"expires_at"`
	EncryptionKeyID         string       `json:"encryption_key_id"`
	CreatedAt               time.Time    `json:"created_at"`
	UpdatedAt               time.Time    `json:"updated_at"`
}

func (q *Queries) StoreCredential(ctx context.Context, arg StoreCredentialParams) error {
	_, err := q.exec(ctx, q.storeCredentialStmt, storeCredential,
		arg.ID,
		arg.IntegrationID,
		arg.CredentialType,
		arg.CredentialDataEncrypted,
		arg.ExpiresAt,
		arg.EncryptionKeyID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE integration_credentials
SET credential_type = $2,
    credential_data_encrypted = $3,
    expires_at = $4,
    encryption_key_id = $5,
    updated_at = NOW()
WHERE integration_id = $1
`

type UpdateCredentialParams struct {
	IntegrationID           uuid.UUID    `json:"integration_id"`
	CredentialType          string       `json:"credential_type"`
	CredentialDataEncrypted string       `json:"credential_data_encrypted"`
	ExpiresAt               sql.NullTime `json:"expires_at"`
	EncryptionKeyID         string       `json:"encryption_key_id"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.exec(ctx, q.updateCredentialStmt, updateCredential,
		arg.IntegrationID,
		arg.CredentialType,
		arg.CredentialDataEncrypted,
		arg.ExpiresAt,
		arg.EncryptionKeyID,
	)
	return err
}
