// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github_repository.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkDeleteGitHubRepositories = `-- name: BulkDeleteGitHubRepositories :exec
DELETE FROM github_repositories 
WHERE integration_id = $1 AND github_repository_id = ANY($2::bigint[])
`

type BulkDeleteGitHubRepositoriesParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Column2       []int64   `json:"column_2"`
}

func (q *Queries) BulkDeleteGitHubRepositories(ctx context.Context, arg BulkDeleteGitHubRepositoriesParams) error {
	_, err := q.exec(ctx, q.bulkDeleteGitHubRepositoriesStmt, bulkDeleteGitHubRepositories, arg.IntegrationID, pq.Array(arg.Column2))
	return err
}

const deleteGitHubRepositoryByGitHubID = `-- name: DeleteGitHubRepositoryByGitHubID :exec
DELETE FROM github_repositories 
WHERE integration_id = $1 AND github_repository_id = $2
`

type DeleteGitHubRepositoryByGitHubIDParams struct {
	IntegrationID      uuid.UUID `json:"integration_id"`
	GithubRepositoryID int64     `json:"github_repository_id"`
}

func (q *Queries) DeleteGitHubRepositoryByGitHubID(ctx context.Context, arg DeleteGitHubRepositoryByGitHubIDParams) error {
	_, err := q.exec(ctx, q.deleteGitHubRepositoryByGitHubIDStmt, deleteGitHubRepositoryByGitHubID, arg.IntegrationID, arg.GithubRepositoryID)
	return err
}

const findGitHubRepositoriesByIntegrationID = `-- name: FindGitHubRepositoriesByIntegrationID :many
SELECT id, integration_id, github_repository_id, repository_name,
    repository_full_name, repository_url, is_private, default_branch,
    permission_admin, permission_push, permission_pull,
    repository_description, repository_language, created_at, updated_at,
    last_synced_at, github_created_at, github_updated_at, github_pushed_at
FROM github_repositories 
WHERE integration_id = $1
ORDER BY repository_full_name
`

func (q *Queries) FindGitHubRepositoriesByIntegrationID(ctx context.Context, integrationID uuid.UUID) ([]GithubRepository, error) {
	rows, err := q.query(ctx, q.findGitHubRepositoriesByIntegrationIDStmt, findGitHubRepositoriesByIntegrationID, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubRepository
	for rows.Next() {
		var i GithubRepository
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.GithubRepositoryID,
			&i.RepositoryName,
			&i.RepositoryFullName,
			&i.RepositoryUrl,
			&i.IsPrivate,
			&i.DefaultBranch,
			&i.PermissionAdmin,
			&i.PermissionPush,
			&i.PermissionPull,
			&i.RepositoryDescription,
			&i.RepositoryLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncedAt,
			&i.GithubCreatedAt,
			&i.GithubUpdatedAt,
			&i.GithubPushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGitHubRepositoryByGitHubID = `-- name: FindGitHubRepositoryByGitHubID :one
SELECT id, integration_id, github_repository_id, repository_name,
    repository_full_name, repository_url, is_private, default_branch,
    permission_admin, permission_push, permission_pull,
    repository_description, repository_language, created_at, updated_at,
    last_synced_at, github_created_at, github_updated_at, github_pushed_at
FROM github_repositories 
WHERE integration_id = $1 AND github_repository_id = $2
`

type FindGitHubRepositoryByGitHubIDParams struct {
	IntegrationID      uuid.UUID `json:"integration_id"`
	GithubRepositoryID int64     `json:"github_repository_id"`
}

func (q *Queries) FindGitHubRepositoryByGitHubID(ctx context.Context, arg FindGitHubRepositoryByGitHubIDParams) (GithubRepository, error) {
	row := q.queryRow(ctx, q.findGitHubRepositoryByGitHubIDStmt, findGitHubRepositoryByGitHubID, arg.IntegrationID, arg.GithubRepositoryID)
	var i GithubRepository
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.GithubRepositoryID,
		&i.RepositoryName,
		&i.RepositoryFullName,
		&i.RepositoryUrl,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.PermissionAdmin,
		&i.PermissionPush,
		&i.PermissionPull,
		&i.RepositoryDescription,
		&i.RepositoryLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSyncedAt,
		&i.GithubCreatedAt,
		&i.GithubUpdatedAt,
		&i.GithubPushedAt,
	)
	return i, err
}

const updateGitHubRepositoryLastSyncTime = `-- name: UpdateGitHubRepositoryLastSyncTime :exec
UPDATE github_repositories 
SET last_synced_at = $1, updated_at = NOW()
WHERE integration_id = $2
`

type UpdateGitHubRepositoryLastSyncTimeParams struct {
	LastSyncedAt  time.Time `json:"last_synced_at"`
	IntegrationID uuid.UUID `json:"integration_id"`
}

func (q *Queries) UpdateGitHubRepositoryLastSyncTime(ctx context.Context, arg UpdateGitHubRepositoryLastSyncTimeParams) error {
	_, err := q.exec(ctx, q.updateGitHubRepositoryLastSyncTimeStmt, updateGitHubRepositoryLastSyncTime, arg.LastSyncedAt, arg.IntegrationID)
	return err
}

const updateGitHubRepositoryPermissions = `-- name: UpdateGitHubRepositoryPermissions :exec
UPDATE github_repositories 
SET permission_admin = $1, 
    permission_push = $2, 
    permission_pull = $3,
    updated_at = NOW()
WHERE integration_id = $4 AND github_repository_id = $5
`

type UpdateGitHubRepositoryPermissionsParams struct {
	PermissionAdmin    bool      `json:"permission_admin"`
	PermissionPush     bool      `json:"permission_push"`
	PermissionPull     bool      `json:"permission_pull"`
	IntegrationID      uuid.UUID `json:"integration_id"`
	GithubRepositoryID int64     `json:"github_repository_id"`
}

func (q *Queries) UpdateGitHubRepositoryPermissions(ctx context.Context, arg UpdateGitHubRepositoryPermissionsParams) error {
	_, err := q.exec(ctx, q.updateGitHubRepositoryPermissionsStmt, updateGitHubRepositoryPermissions,
		arg.PermissionAdmin,
		arg.PermissionPush,
		arg.PermissionPull,
		arg.IntegrationID,
		arg.GithubRepositoryID,
	)
	return err
}

const upsertGitHubRepository = `-- name: UpsertGitHubRepository :exec

INSERT INTO github_repositories (
    id, integration_id, github_repository_id, repository_name,
    repository_full_name, repository_url, is_private, default_branch,
    permission_admin, permission_push, permission_pull,
    repository_description, repository_language, created_at, updated_at,
    last_synced_at, github_created_at, github_updated_at, github_pushed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
ON CONFLICT (integration_id, github_repository_id)
DO UPDATE SET
    repository_name = EXCLUDED.repository_name,
    repository_full_name = EXCLUDED.repository_full_name,
    repository_url = EXCLUDED.repository_url,
    is_private = EXCLUDED.is_private,
    default_branch = EXCLUDED.default_branch,
    permission_admin = EXCLUDED.permission_admin,
    permission_push = EXCLUDED.permission_push,
    permission_pull = EXCLUDED.permission_pull,
    repository_description = EXCLUDED.repository_description,
    repository_language = EXCLUDED.repository_language,
    updated_at = EXCLUDED.updated_at,
    last_synced_at = EXCLUDED.last_synced_at,
    github_updated_at = EXCLUDED.github_updated_at,
    github_pushed_at = EXCLUDED.github_pushed_at
`

type UpsertGitHubRepositoryParams struct {
	ID                    uuid.UUID      `json:"id"`
	IntegrationID         uuid.UUID      `json:"integration_id"`
	GithubRepositoryID    int64          `json:"github_repository_id"`
	RepositoryName        string         `json:"repository_name"`
	RepositoryFullName    string         `json:"repository_full_name"`
	RepositoryUrl         string         `json:"repository_url"`
	IsPrivate             bool           `json:"is_private"`
	DefaultBranch         sql.NullString `json:"default_branch"`
	PermissionAdmin       bool           `json:"permission_admin"`
	PermissionPush        bool           `json:"permission_push"`
	PermissionPull        bool           `json:"permission_pull"`
	RepositoryDescription sql.NullString `json:"repository_description"`
	RepositoryLanguage    sql.NullString `json:"repository_language"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	LastSyncedAt          time.Time      `json:"last_synced_at"`
	GithubCreatedAt       sql.NullTime   `json:"github_created_at"`
	GithubUpdatedAt       sql.NullTime   `json:"github_updated_at"`
	GithubPushedAt        sql.NullTime   `json:"github_pushed_at"`
}

// GitHub Repository Queries
func (q *Queries) UpsertGitHubRepository(ctx context.Context, arg UpsertGitHubRepositoryParams) error {
	_, err := q.exec(ctx, q.upsertGitHubRepositoryStmt, upsertGitHubRepository,
		arg.ID,
		arg.IntegrationID,
		arg.GithubRepositoryID,
		arg.RepositoryName,
		arg.RepositoryFullName,
		arg.RepositoryUrl,
		arg.IsPrivate,
		arg.DefaultBranch,
		arg.PermissionAdmin,
		arg.PermissionPush,
		arg.PermissionPull,
		arg.RepositoryDescription,
		arg.RepositoryLanguage,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSyncedAt,
		arg.GithubCreatedAt,
		arg.GithubUpdatedAt,
		arg.GithubPushedAt,
	)
	return err
}
