// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package postgres

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (clerk_user_id, email, first_name, last_name)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ClerkUserID string `json:"clerk_user_id"`
	Email       string `json:"email"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.exec(ctx, q.createUserStmt, createUser,
		arg.ClerkUserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	return err
}

const deleteUserByClerkID = `-- name: DeleteUserByClerkID :exec
DELETE FROM users
WHERE clerk_user_id = $1
`

func (q *Queries) DeleteUserByClerkID(ctx context.Context, clerkUserID string) error {
	_, err := q.exec(ctx, q.deleteUserByClerkIDStmt, deleteUserByClerkID, clerkUserID)
	return err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, first_name, last_name, created_at, updated_at
FROM users
WHERE clerk_user_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.queryRow(ctx, q.getUserByClerkIDStmt, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $2, first_name = $3, last_name = $4, updated_at = NOW()
WHERE clerk_user_id = $1
`

type UpdateUserParams struct {
	ClerkUserID string `json:"clerk_user_id"`
	Email       string `json:"email"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.exec(ctx, q.updateUserStmt, updateUser,
		arg.ClerkUserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	return err
}
