# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x8d\x01\n\x0c\x41gentRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63urrent_message\x18\x02 \x01(\t\x12\x15\n\rpast_messages\x18\x03 \x03(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x12\n\nchannel_id\x18\x06 \x01(\t\"\x8a\x01\n\rAgentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rresponse_text\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x12\n\nagent_type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\ntools_used\x18\x06 \x03(\t2K\n\x0c\x41gentService\x12;\n\x0eProcessMessage\x12\x13.agent.AgentRequest\x1a\x14.agent.AgentResponseB8Z6github.com/priyanshujain/infragpt/services/agent/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/priyanshujain/infragpt/services/agent/proto'
  _globals['_AGENTREQUEST']._serialized_start=23
  _globals['_AGENTREQUEST']._serialized_end=164
  _globals['_AGENTRESPONSE']._serialized_start=167
  _globals['_AGENTRESPONSE']._serialized_end=305
  _globals['_AGENTSERVICE']._serialized_start=307
  _globals['_AGENTSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
